### ISSUE TITLE
Actuator not working with latest version

### ISSUE THREAD

**Issue by wtiann** [esanchezros/quickfixj-spring-boot-starter#116]
The actuator's endpoint configuration is relying on `QuickFixJClientConfiguration` which is deprecated.  if i use the new way to enable client or server this means this bean not enabled. The actuator is not working in this case.
```@Configuration(proxyBeanMethods = false)
@AutoConfigureAfter(QuickFixJClientConfiguration.class)
public class QuickFixJClientEndpointAutoConfiguration
```

Another issue is if i have muliple sessions, it only show one `sessionSchedule` in the health endpoint

**Comment by esanchezros** [comment]
@wtiann I've released https://github.com/esanchezros/quickfixj-spring-boot-starter/releases/tag/2.16.2 with the fix for the bug you raised. Please note enabling the actuator with the new way will need `quickfixj.client.actuator.enable=true` or `quickfixj.server.actuator.enabled=true` in the properties
