### ISSUE TITLE
fix5.0sp1 gets market price anomalies

### ISSUE THREAD

**Issue by DUZHANGYI** [esanchezros/quickfixj-spring-boot-starter#118]
Hello, when I subscribe to the market price of fix5.0sp1, toadmin 58=Tag not defined for this message type, field=55 appears. I want to know what is the reason, thank you

**Comment by esanchezros** [comment]
Hi @DUZHANGYI, the quickfixj spring boot starter is just a wrapper around the quickfixj library which handles the connection, session and sending of messages to the exchange. For the error description, it seems you did not send the subscription to the market price (https://www.onixs.biz/fix-dictionary/5.0.sp1/tagnum_55.html). Try adding the Symbol to the request and see if that fixes your problem. 

Will close as this issue is not related to the library

**Comment by DUZHANGYI** [comment]
I'm glad to hear from you
Here are the responses I sent and received


8=FIXT.1.19=18535=V34=349=ATLTD52=20231117-00:29:08.37256=PRD-ATLTD262=icbc-rate-sub-XAU/USD-1263=1264=1265=11070=0146=155=XAU/USD167=FOR15=USD63=0267=2269=0269=110=118
8=FIXT.1.19=49935=X34=449=PRD-ATLTD52=20231117-00:29:11.97656=ATLTD1128=855=XAU/USD262=icbc-rate-sub-XAU/USD-1268=2279=0269=0278=icbc-rate-sub-XAU/USD-1 XAU.USD=20231117002911120.00 4Pa.2FDBBC7D270=1981.88126=20231117-00:31:11.975299=1:FX.CROSS.XAU.USD.SPOT63=064=202311211070=01026=1981.88279=0269=1278=icbc-rate-sub-XAU/USD-1 XAU.USD=20231117002911120.00 4Pa.2FDBBC7F270=1982.19126=20231117-00:31:11.975299=1:FX.CROSS.XAU.USD.SPOT63=064=202311211070=01026=1982.1910=135



But MarketDataIncrementalRefresh type of message does not appear in the onMessage MessageCracker

My idea console keeps popping error&gt; (Reject sent for message 4: Tag not defined for this message type, field=55)

I wonder what the reason is
Looking forward to your reply

**Comment by DUZHANGYI** [comment]
@esanchezros ValidateFieldsOutOfOrder=N
ValidateUserDefinedFields=N
ValidateUnorderedGroupFields=N
ValidateIncomingMessage=N
AllowUnknownMsgFields=Y
RejectGarbledMessage=N
RejectInvalidMessage=N
After adding the above configuration, it was solved. Thank you very much for your previous reply.
