### ISSUE TITLE
Example to implement Log with JDBC

### ISSUE THREAD

**Issue by robertfernanV** [esanchezros/quickfixj-spring-boot-starter#34]
Hi! i using this library is great! but i have a litte problem with configurate login with JDBC in config i have all options with JDBC Login but the application dont regrister anythinks readings blogs of quickfix i find the next one http://quickfix-j.364392.n2.nabble.com/JDBC-storage-not-working-properly-td364865.html "Stephen Bate" Saids : "Because you are using a ScreenLogFactory, all logging is going to
the standard output (console). To use database logging, use the
JdbcLogFactory instead." when i try configurate  ThreadedSocketInitiator with JdbcLogFactory the application crash. any have a litte example to use this library with JDBC? Thanks

**Comment by esanchezros** [comment]
Hi Roberto,
What error are you getting when the app crashes? Could you put your code in github so I can have a look?
    En martes, 17 de marzo de 2020 15:51:32 CET, Roberto Fernandez <notifications@github.com> escribió:  
 
 


Hi! i using this library is great! but i have a litte problem with configurate login with JDBC in config i have all options with JDBC Login but the application dont regrister anythinks readings blogs of quickfix i find the next one http://quickfix-j.364392.n2.nabble.com/JDBC-storage-not-working-properly-td364865.html "Stephen Bate" Saids : "Because you are using a ScreenLogFactory, all logging is going to
the standard output (console). To use database logging, use the
JdbcLogFactory instead." when i try configurate ThreadedSocketInitiator with JdbcLogFactory the application crash. any have a litte example to use this library with JDBC? Thanks

**Comment by robertfernanV** [comment]
@esanchezros Hi! thanks for response! take a look
![image](https://user-images.githubusercontent.com/13409353/76874799-76e9e800-684e-11ea-808f-8a993f72edcd.png)

I know what the class MessageStoreFactory cannot cast to JdbcLogFactory, buy my question is how put JdbcLogFactory in ThreadedSocketInitiator or where put  JdbcLogFactory in the configuration of  this? Maybe, Do i have extends for any Interface?

**Comment by esanchezros** [comment]
Hi Roberto,
I can't see the cause Exception, could you copy and paste the full stacktrace and the class code?
Thanks
    En martes, 17 de marzo de 2020 16:57:40 CET, Roberto Fernandez <notifications@github.com> escribió:  
 
 


@esanchezros Hi! thanks for response! take a look


I know what the class MessageStoreFactory cannot cast to JdbcLogFactory, buy my question is how put JdbcLogFactory in ThreadedSocketInitiator or where put JdbcLogFactory in the configuration of this? Maybe, Do i have extends for any Interface?

**Comment by robertfernanV** [comment]
Ok the  full stacktrace:

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hearbeatController': Unsatisfied dependency expressed through field 'clientInitiator'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'quickfix.ThreadedSocketInitiator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.intl.main.DemoApplication.main(DemoApplication.java:43) ~[classes/:na]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'quickfix.ThreadedSocketInitiator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1695) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1292) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 19 common frames omitted`

And Class code:

`import io.allune.quickfixj.spring.boot.starter.EnableQuickFixJClient;
import lombok.extern.slf4j.Slf4j;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

import quickfix.Application;
import quickfix.ConfigError;
import quickfix.FileLogFactory;
import quickfix.JdbcLogFactory;
import quickfix.LogFactory;
import quickfix.MessageFactory;
import quickfix.MessageStore;
import quickfix.MessageStoreFactory;
import quickfix.SLF4JLogFactory;
import quickfix.SessionSettings;
import quickfix.ThreadedSocketInitiator;


@EnableQuickFixJClient
@SpringBootApplication
public class DemoApplication implements CommandLineRunner {
    
    

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
        
    @Override
    public void run(String... args) throws Exception {
        System.out.println("Joining thread, you can press Ctrl+C to shutdown application");
        //Helper.fixToJson("8=FIXT.1.19=14635=A34=149=MAEFIXSORIntlCibsa52=20200313-18:59:03.76256=MAEFIXSORServerHomo98=0108=30141=Y553=FIXMDFIntlCibsa554=?5qN#.Vn4uQDh@Ey1137=910=172");

        /*LoginRequest lr = new LoginRequest();
        System.out.println("com.intl.main.DemoApplication.run()");
        System.out.println("com.intl.main.DemoApplication.run() "+lr.login().toString());*/
        Thread.currentThread().join();
    }

    @Bean
    public Application clientApplication() {
            return new FixInterface();
    }

    @Bean
    public ThreadedSocketInitiator clientInitiator(quickfix.Application clientApplication, MessageStoreFactory clientMessageStoreFactory,
                SessionSettings clientSessionSettings, LogFactory clientLogFactory,
                    MessageFactory clientMessageFactory) {
        
         ThreadedSocketInitiator t = null;
            try{
                 MessageStoreFactory messageStoreFactory = (MessageStoreFactory) new JdbcLogFactory(clientSessionSettings);
                 
                //MessageStoreFactory messageStoreFactory = (MessageStoreFactory) new SynchronizedMessageStore((MessageStore) clientMessageStoreFactory);


		t = new ThreadedSocketInitiator(clientApplication,messageStoreFactory , clientSessionSettings, 
				clientLogFactory, clientMessageFactory);
                
            }catch(ConfigError ex){
                System.out.println("ERROR CONFIG "+ex.getMessage());
                
            } finally{
                System.out.println("DemoApplication.clientInitiator()");
                return t;
            }
        
            /*return new ThreadedSocketInitiator(clientApplication, clientMessageStoreFactory, clientSessionSettings,
                            clientLogFactory, clientMessageFactory);*/
    }

    @Bean
    public LogFactory clientLogFactory(SessionSettings clientSessionSettings) {
        //return new SLF4JLogFactory(clientSessionSettings);
            return new FileLogFactory(clientSessionSettings);
    }

    @Bean
    public String testString(){
        return "ArmyOfOne";
    }

    @EnableWebSecurity
    @Configuration
    class WebSecurityConfig extends WebSecurityConfigurerAdapter{
            @Override
            protected void configure(HttpSecurity http) throws Exception {
                    http.csrf().disable()
                    .addFilterAfter(new JWTAuthorizationFilter(), UsernamePasswordAuthenticationFilter.class)
                    .authorizeRequests()
                    .antMatchers(HttpMethod.POST, "/user").permitAll()
                    .anyRequest().authenticated();
            }
    }

}
`

**Comment by esanchezros** [comment]
Hi Roberto, 
Are you trying to override the `LogFactory` or the `MessageStoreFactory`? 
LogFactory logFactory = (LogFactory) new JdbcLogFactory(clientSessionSettings);Regards 
Sent from Yahoo Mail on Android 
 
  On Tue, 17 Mar 2020 at 17:12, Roberto Fernandez<notifications@github.com> wrote:   


Ok the full stacktrace:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hearbeatController': Unsatisfied dependency expressed through field 'clientInitiator'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'quickfix.ThreadedSocketInitiator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)} at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at com.intl.main.DemoApplication.main(DemoApplication.java:43) ~[classes/:na] Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'quickfix.ThreadedSocketInitiator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)} at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1695) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1292) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] ... 19 common frames omitted

And Class code:

`import io.allune.quickfixj.spring.boot.starter.EnableQuickFixJClient;
import lombok.extern.slf4j.Slf4j;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

import quickfix.Application;
import quickfix.ConfigError;
import quickfix.FileLogFactory;
import quickfix.JdbcLogFactory;
import quickfix.LogFactory;
import quickfix.MessageFactory;
import quickfix.MessageStore;
import quickfix.MessageStoreFactory;
import quickfix.SLF4JLogFactory;
import quickfix.SessionSettings;
import quickfix.ThreadedSocketInitiator;

@EnableQuickFixJClient
@SpringBootApplication
public class DemoApplication implements CommandLineRunner {
public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
}
    
@Override
public void run(String... args) throws Exception {
    System.out.println("Joining thread, you can press Ctrl+C to shutdown application");
    //Helper.fixToJson("8=FIXT.1.1�9=146�35=A�34=1�49=MAEFIXSORIntlCibsa�52=20200313-18:59:03.762�56=MAEFIXSORServerHomo�98=0�108=30�141=Y�553=FIXMDFIntlCibsa�554=?5qN#.Vn4uQDh@Ey�1137=9�10=172�");

    /*LoginRequest lr = new LoginRequest();
    System.out.println("com.intl.main.DemoApplication.run()");
    System.out.println("com.intl.main.DemoApplication.run() "+lr.login().toString());*/
    Thread.currentThread().join();
}

@Bean
public Application clientApplication() {
        return new FixInterface();
}

@Bean
public ThreadedSocketInitiator clientInitiator(quickfix.Application clientApplication, MessageStoreFactory clientMessageStoreFactory,
            SessionSettings clientSessionSettings, LogFactory clientLogFactory,
                MessageFactory clientMessageFactory) {
    
     ThreadedSocketInitiator t = null;
        try{
             MessageStoreFactory messageStoreFactory = (MessageStoreFactory) new JdbcLogFactory(clientSessionSettings);
             
            //MessageStoreFactory messageStoreFactory = (MessageStoreFactory) new SynchronizedMessageStore((MessageStore) clientMessageStoreFactory);


	t = new ThreadedSocketInitiator(clientApplication,messageStoreFactory , clientSessionSettings, 
			clientLogFactory, clientMessageFactory);
            
        }catch(ConfigError ex){
            System.out.println("ERROR CONFIG "+ex.getMessage());
            
        } finally{
            System.out.println("DemoApplication.clientInitiator()");
            return t;
        }
    
        /*return new ThreadedSocketInitiator(clientApplication, clientMessageStoreFactory, clientSessionSettings,
                        clientLogFactory, clientMessageFactory);*/
}

@Bean
public LogFactory clientLogFactory(SessionSettings clientSessionSettings) {
    //return new SLF4JLogFactory(clientSessionSettings);
        return new FileLogFactory(clientSessionSettings);
}

@Bean
public String testString(){
    return "ArmyOfOne";
}

@EnableWebSecurity
@Configuration
class WebSecurityConfig extends WebSecurityConfigurerAdapter{
        @Override
        protected void configure(HttpSecurity http) throws Exception {
                http.csrf().disable()
                .addFilterAfter(new JWTAuthorizationFilter(), UsernamePasswordAuthenticationFilter.class)
                .authorizeRequests()
                .antMatchers(HttpMethod.POST, "/user").permitAll()
                .anyRequest().authenticated();
        }
}

}
`

**Comment by robertfernanV** [comment]
@esanchezros  can you delete all code plz?

**Comment by robertfernanV** [comment]
@esanchezros have any keys sorry my bad!

**Comment by esanchezros** [comment]
Did you get your issue resolved

**Comment by robertfernanV** [comment]
@esanchezros  Your advice helped me a lot,  Here is an example for someone in the future:

```
 @Bean
    public LogFactory clientLogFactory(SessionSettings clientSessionSettings) {
        LogFactory logFactory;
        
        JdbcLogFactory messageStoreFactory = new JdbcLogFactory(clientSessionSettings);
        FileLogFactory l = new FileLogFactory(clientSessionSettings);
        
        JdbcStoreFactory objJSF = new JdbcStoreFactory(clientSessionSettings);
        JdbcLogFactory objJLF = new JdbcLogFactory(clientSessionSettings);
        JtdsDataSource ds = new JtdsDataSource();
        ds.setServerName(SERVERNAME);
        ds.setDatabaseName(DATABASENAME);
        ds.setInstance(INSTANCE-NAME);
        ds.setUser(USER);
        ds.setPassword(PASSWORD);
        objJSF.setDataSource(ds);
        objJLF.setDataSource(ds);
        logFactory = objJLF;
        
        return logFactory;
    }
```

I use net.sourceforge.jtds.jdbc.Driver and the cfg i dont write anythink

**Comment by robertfernanV** [comment]
> @esanchezros can you delete all code plz?

**Comment by robertfernanV** [comment]
> Hi Roberto,  Are you trying to override the `LogFactory` or the `MessageStoreFactory`? LogFactory logFactory = (LogFactory) new JdbcLogFactory(clientSessionSettings);Regards  Sent from Yahoo Mail on Android On Tue, 17 Mar 2020 at 17:12, Roberto Fernandez<notifications@github.com> wrote: Ok the full stacktrace: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hearbeatController': Unsatisfied dependency expressed through field 'clientInitiator'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'quickfix.ThreadedSocketInitiator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)} at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE] at com.intl.main.DemoApplication.main(DemoApplication.java:43) ~[classes/:na] Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'quickfix.ThreadedSocketInitiator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)} at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1695) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1292) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE] ... 19 common frames omitted And Class code: `import io.allune.quickfixj.spring.boot.starter.EnableQuickFixJClient; import lombok.extern.slf4j.Slf4j; import org.springframework.boot.CommandLineRunner; import org.springframework.boot.SpringApplication; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.boot.web.client.RestTemplateBuilder; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import org.springframework.http.HttpMethod; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity; import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import quickfix.Application; import quickfix.ConfigError; import quickfix.FileLogFactory; import quickfix.JdbcLogFactory; import quickfix.LogFactory; import quickfix.MessageFactory; import quickfix.MessageStore; import quickfix.MessageStoreFactory; import quickfix.SLF4JLogFactory; import quickfix.SessionSettings; import quickfix.ThreadedSocketInitiator; @EnableQuickFixJClient @SpringBootApplication public class DemoApplication implements CommandLineRunner { public static void main(String[] args) { SpringApplication.run(DemoApplication.class, args); } @override public void run(String... args) throws Exception { System.out.println("Joining thread, you can press Ctrl+C to shutdown application"); /*LoginRequest lr = new LoginRequest(); System.out.println("com.intl.main.DemoApplication.run()"); System.out.println("com.intl.main.DemoApplication.run() "+lr.login().toString());*/ Thread.currentThread().join(); } @bean public Application clientApplication() { return new FixInterface(); } @bean public ThreadedSocketInitiator clientInitiator(quickfix.Application clientApplication, MessageStoreFactory clientMessageStoreFactory, SessionSettings clientSessionSettings, LogFactory clientLogFactory, MessageFactory clientMessageFactory) { ThreadedSocketInitiator t = null; try{ MessageStoreFactory messageStoreFactory = (MessageStoreFactory) new JdbcLogFactory(clientSessionSettings); //MessageStoreFactory messageStoreFactory = (MessageStoreFactory) new SynchronizedMessageStore((MessageStore) clientMessageStoreFactory); t = new ThreadedSocketInitiator(clientApplication,messageStoreFactory , clientSessionSettings, clientLogFactory, clientMessageFactory); }catch(ConfigError ex){ System.out.println("ERROR CONFIG "+ex.getMessage()); } finally{ System.out.println("DemoApplication.clientInitiator()"); return t; } /*return new ThreadedSocketInitiator(clientApplication, clientMessageStoreFactory, clientSessionSettings, clientLogFactory, clientMessageFactory);*/ } @bean public LogFactory clientLogFactory(SessionSettings clientSessionSettings) { //return new SLF4JLogFactory(clientSessionSettings); return new FileLogFactory(clientSessionSettings); } @bean public String testString(){ return "ArmyOfOne"; } @EnableWebSecurity @configuration class WebSecurityConfig extends WebSecurityConfigurerAdapter{ @override protected void configure(HttpSecurity http) throws Exception { http.csrf().disable() .addFilterAfter(new JWTAuthorizationFilter(), UsernamePasswordAuthenticationFilter.class) .authorizeRequests() .antMatchers(HttpMethod.POST, "/user").permitAll() .anyRequest().authenticated(); } } } ` — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

please delete the code! thanks
