### ISSUE TITLE
'Socket reads suspended' while trying to establish FIX connection

### ISSUE THREAD

**Issue by aniket0788** [esanchezros/quickfixj-spring-boot-starter#45]
Getting the below snippet in logs (both initiator and acceptor) while establishing a FIX connection using quickfixj-spring-boot-starter

`<20200709-17:57:30, FIX.4.4:client->server, event> (inbound queue size > upper watermark (-1), socket reads suspended)`

because of this FIX engine is not receiving any messages (fromApp is not getting called !)

Could you please have a look?

Thanks

**Comment by esanchezros** [comment]
Could you upload the code to GitHub? I've never seen this error before but got the feeling it may be down to incorrect configuration (inbound queue size?)

Sent from Yahoo Mail on Android 
 
  On Thu, 9 Jul 2020 at 20:08, aniket0788<notifications@github.com> wrote:   


Getting the below snippet in logs (both initiator and acceptor) while establishing a FIX connection using quickfixj-spring-boot-starter

<20200709-17:57:30, FIX.4.4:client->server, event> (inbound queue size > upper watermark (-1), socket reads suspended)

because of this FIX engine is not receiving any messages (fromApp is not getting called !)

Could you please have a look?

Thanks

**Comment by aniket0788** [comment]
you are right.. there was a problem in the configuration of data dictionary.
Closing this issue.
