### ISSUE TITLE
Add support for FIX50SP2 when sending messages with QuickFixJTemplate

### ISSUE THREAD

**Issue by raj75017** [esanchezros/quickfixj-spring-boot-starter#58]
getApplicationVersionID(Session session) in QuickFixJTemplate always returns ApplVerID.FIX50 when BeginString = FixVersions.BEGINSTRING_FIXT11

This means FIX50SP1 or FIX50SP2 are not supported.

Modify logic accordingly to support them otherwise valid messages in FIX50SP2 are incorrectly treated as invalid messages e.g.
167=IRS is valid in FIX50SP2 but invalid in FIX50

**Comment by esanchezros** [comment]
Hi @raj75017 

Thanks for raising the bug. I think this was an oversight when creating the `QuickFixJTemplate`. Now, I'm wondering the correct logic to use in determining the value for `ApplVerID`, if `BeginString` is equals to `BEGINSTRING_FIXT11`:

- Take the value of `ApplVerID` on the `Message`.
- If `ApplVerID` is not specified on the message (I believe it's mandatory but it may not be included), use the value of `DefaultApplVerID` in `Session`.
- Otherwise default to `FIX50`.

Let me know if you have any other case of suggestion.

**Comment by raj75017** [comment]
Yes I think your proposed logic would work (at least for the scenarios I can think of!)

Thanks @esanchezros

**Comment by esanchezros** [comment]
Fixed on version 2.7.1
